## 세팅

In [ ]:
# 필요한 libraries import하기
import pandas as pd
import numpy as np
import os

In [ ]:
from google.colab import drive
drive.mount('/content/drive')
os.chdir('/content/drive/MyDrive/')

# 데이터 셋 불러오기
ratings_df = pd.read_csv("ratings_two.csv")
reviews_df = pd.read_csv("reviews_two.csv")
users_df = pd.read_csv("users.csv")

Mounted at /content/drive

## 데이터 확인

In [ ]:
# 사용자 데이터셋
users_df.head()

   user_id       user_name  user_review_num  user_rating_avg
0   7t5a08            xoxo               13              3.4
1   8pl2n9  맑은물 맑은공기 깨끗한환경                2              5.0
2  108t0l1             이혁준                1              5.0
3   ghd8jt            june               75              3.7
4   tt6hvd            맛집킬러              198              2.9

In [ ]:
users_df.describe()

       user_review_num  user_rating_avg
count     32821.000000     32821.000000
mean         26.266171         3.818415
std          58.597543         1.131129
min           1.000000         1.000000
25%           2.000000         3.100000
50%           8.000000         4.000000
75%          25.000000         5.000000
max         995.000000         5.000000

In [ ]:
# 카페 별 리뷰 데이터셋
reviews_df.head()

,name,address,user_id,rating,review,cafe
0,공차 이대익스프레스점,대현동,100ck0j,1.0,밑에 후기에 노란색탈색머리 알바 불친절하다고 그랬는데\n진짜 그러네요 내돈주고 사먹...,공차 이대익스프레스점 대현동
1,투썸플레이스 숙대입구역점,남영동,100ck0j,1.0,최애 케이크가 투썸 스트로베리초콜릿케이크라서 엄청 많이 먹어봤는데 이렇게 맛없는 케...,투썸플레이스 숙대입구역점 남영동
2,폴바셋 방배역점,방배동,100ck0j,5.0,직원분들 전부 친절하시고 주차도 가능해서 이용하기에 좋아요:) 주차 관리인 아저씨도...,폴바셋 방배역점 방배동
3,고로커피로스터스,봉천동,100i22n,4.0,커피랑 원두 맛남,고로커피로스터스 봉천동
4,나따오비까 대치점,대치동,100i22n,3.0,에그타르트 클래식 ☆☆☆\n에그타르트 크림치즈 ☆☆☆.5\n\n시나몬향이 나고 빵 ...,나따오비까 대치점 대치동

In [ ]:
reviews_df.describe()

             rating
count  20069.000000
mean       3.816633
std        1.433970
min        1.000000
25%        3.000000
50%        4.000000
75%        5.000000
max        5.000000

In [ ]:
# 평점 데이터셋
ratings_df.head()

,name,address,user_id,rating,review,cafe
0,3F로비,한강로3가,100bln7,5.0,NaN,3F로비 한강로3가
1,카페로비,한강로3가,100bln7,5.0,NaN,카페로비 한강로3가
2,공차 이대익스프레스점,대현동,100ck0j,1.0,밑에 후기에 노란색탈색머리 알바 불친절하다고 그랬는데\n진짜 그러네요 내돈주고 사먹...,공차 이대익스프레스점 대현동
3,투썸플레이스 숙대입구역점,남영동,100ck0j,1.0,최애 케이크가 투썸 스트로베리초콜릿케이크라서 엄청 많이 먹어봤는데 이렇게 맛없는 케...,투썸플레이스 숙대입구역점 남영동
4,폴바셋 방배역점,방배동,100ck0j,5.0,직원분들 전부 친절하시고 주차도 가능해서 이용하기에 좋아요:) 주차 관리인 아저씨도...,폴바셋 방배역점 방배동

In [ ]:
ratings_df.describe()

             rating
count  23952.000000
mean       3.843854
std        1.425506
min        1.000000
25%        3.000000
50%        4.000000
75%        5.000000
max        5.000000

## 데이터 재구성

In [ ]:
# 평점 데이터에서 user_id, 카페명, 평점만 가져오기
ratings = ratings_df[['user_id', 'cafe', 'rating']]
ratings['rating'] = ratings['rating'].astype(int)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [ ]:
ratings.head()

   user_id               cafe  rating
0  100bln7         3F로비 한강로3가       5
1  100bln7         카페로비 한강로3가       5
2  100ck0j    공차 이대익스프레스점 대현동       1
3  100ck0j  투썸플레이스 숙대입구역점 남영동       1
4  100ck0j       폴바셋 방배역점 방배동       5

In [ ]:
# 카페명과 주소 빼고 다른 데이터 제거
cafes = ratings_df[['name', 'address']]

In [ ]:
cafes.head()

            name address
0           3F로비   한강로3가
1           카페로비   한강로3가
2    공차 이대익스프레스점     대현동
3  투썸플레이스 숙대입구역점     남영동
4       폴바셋 방배역점     방배동

### train, test set

In [ ]:
# train, test 데이터 분리
from sklearn.model_selection import train_test_split
x = ratings.copy()
y = ratings['user_id']
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.35, stratify=y)

In [ ]:
x.head()

   user_id               cafe  rating
0  100bln7         3F로비 한강로3가       5
1  100bln7         카페로비 한강로3가       5
2  100ck0j    공차 이대익스프레스점 대현동       1
3  100ck0j  투썸플레이스 숙대입구역점 남영동       1
4  100ck0j       폴바셋 방배역점 방배동       5

In [ ]:
y.head()

0    100bln7
1    100bln7
2    100ck0j
3    100ck0j
4    100ck0j
Name: user_id, dtype: object

In [ ]:
x_train.head()

       user_id             cafe  rating
20102   o942fi  오핀카페 영등포점 문래동3가       4
19850   ns3lrb    설빙 홍대입구역점 동교동       2
21696   t49egg     커피베이 중곡점 중곡동       5
871    115h6bn       오프커피 성수동2가       4
6894   1dqj9s7        맥심플랜트 한남동       4

In [ ]:
x_test.head()

       user_id               cafe  rating
19074   n1v704    센터커피 서울숲점 성수동1가       1
18332   muqlcq            키라쿠 제기동       4
22576   uf437v           니피커피 봉천동       5
1402   11vtfn7  스타벅스 송파나루역DT점 송파동       1
12609   e4i5q4          미완성식탁 망원동       5

In [ ]:
y_train.head()

20102     o942fi
19850     ns3lrb
21696     t49egg
871      115h6bn
6894     1dqj9s7
Name: user_id, dtype: object

In [ ]:
y_test.head()

19074     n1v704
18332     muqlcq
22576     uf437v
1402     11vtfn7
12609     e4i5q4
Name: user_id, dtype: object

In [ ]:
# train 데이터로 Full matrix 구하기 
rating_matrix = x_train.pivot(index='user_id', columns='cafe', values='rating').fillna(0)

In [ ]:
rating_matrix.head()

cafe,044워리어스 당산동1가,089커피앤베이커리 화곡동,1028커피엔디저트 성내동,10인치샌드위치&커피 봉천동,125coffee 갈현동,139COFFEE 전농동,1월의윤슬 내발산동,205도씨 명륜2가,212베이크샵 마곡동,24시무인카페더웨일 창동,...,히어로보드게임카페 홍대1호점 서교동,히어로보드게임카페 홍대2호점 동교동,히어로스터 신도림동,히얼스유알커피 삼성동,히자우 홍제동,히포커피 대학동점 신림동,히포커피서울대점 서울대점 신림동,히히냥냥 역삼동,힐브레드 마곡동,힘들땐마카롱 신당동
user_id,,,,,,,,,,,,,,,,,,,,,
100bln7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
100ck0j,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
100i22n,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
100ooji,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
100q04c,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

### 함수 정의 (RMSE, 코사인 유사도, 예측치 계산)

In [ ]:
# train set 사용자들의 Cosine similarities 계산
from sklearn.metrics.pairwise import cosine_similarity
matrix_dummy = rating_matrix.copy().fillna(0)
user_similarity = cosine_similarity(matrix_dummy, matrix_dummy)
user_similarity = pd.DataFrame(user_similarity, index=rating_matrix.index, columns=rating_matrix.index)

In [ ]:
# 정확도(RMSE)를 계산하는 함수 
def RMSE(y_true, y_pred):
    return np.sqrt(np.mean((np.array(y_true) - np.array(y_pred))**2))

# 모델별 RMSE를 계산하는 함수 
def score(model, neighbor_size=0):
    id_pairs = zip(x_test['user_id'], x_test['cafe'])
    y_pred = np.array([model(user, cafe, neighbor_size) for (user, cafe) in id_pairs])
    y_true = np.array(x_test['rating'])
    return RMSE(y_true, y_pred)

In [ ]:
# Neighbor size를 정해서 예측치를 계산하는 함수 
def cf_knn(user_id, cafe, neighbor_size=0):
    if cafe in rating_matrix:
        # 현재 사용자와 다른 사용자 간의 similarity 가져오기
        sim_scores = user_similarity[user_id].copy()
        # 현재 카페에 대한 모든 사용자의 rating값 가져오기
        cafe_ratings = rating_matrix[cafe].copy()
        # 현재 카페를 평가하지 않은 사용자의 index 가져오기
        none_rating_idx = cafe_ratings[cafe_ratings.isnull()].index
        # 현재 카페를 평가하지 않은 사용자의 rating (null) 제거
        cafe_ratings = cafe_ratings.drop(none_rating_idx)
        # 현재 카페를 평가하지 않은 사용자의 similarity값 제거
        sim_scores = sim_scores.drop(none_rating_idx)
##### Neighbor size가 지정되지 않은 경우        
        if neighbor_size == 0:          
            # 현재 카페를 평가한 모든 사용자의 가중평균값 구하기
            mean_rating = np.dot(sim_scores, cafe_ratings) / sim_scores.sum()
##### Neighbor size가 지정된 경우
        else:                       
            # 해당 카페를 평가한 사용자가 최소 2명이 되는 경우에만 계산
            if len(sim_scores) > 1: 
                # 지정된 neighbor size 값과 해당 카페를 평가한 총사용자 수 중 작은 것으로 결정
                neighbor_size = min(neighbor_size, len(sim_scores))
                # array로 바꾸기 (argsort를 사용하기 위함)
                sim_scores = np.array(sim_scores)
                cafe_ratings = np.array(cafe_ratings)
                # 유사도를 순서대로 정렬
                user_idx = np.argsort(sim_scores)
                # 유사도를 neighbor size만큼 받기
                sim_scores = sim_scores[user_idx][-neighbor_size:]
                # 카페 rating을 neighbor size만큼 받기
                cafe_ratings = cafe_ratings[user_idx][-neighbor_size:]
                # 최종 예측값 계산 
                mean_rating = np.dot(sim_scores, cafe_ratings) / sim_scores.sum()
            else:
                mean_rating = 3.0
    else:
        mean_rating = 3.0
    return mean_rating

In [ ]:
# 정확도 계산
score(cf_knn, neighbor_size=30)

3.8330406653778324

### CF 정확도 개선 1

#### 최적의 이웃 크기 구하기

In [ ]:
##### 최적의 neighbor size 구하기

# train set으로 full matrix와 cosine similarity 구하기 
rating_matrix = x_train.pivot_table(values='rating', index='user_id', columns='cafe').fillna(0)
from sklearn.metrics.pairwise import cosine_similarity
matrix_dummy = rating_matrix.copy().fillna(0)
user_similarity = cosine_similarity(matrix_dummy, matrix_dummy)
user_similarity = pd.DataFrame(user_similarity, index=rating_matrix.index, columns=rating_matrix.index)
for neighbor_size in [10, 20, 30, 40, 50, 60]:
    print("Neighbor size = %d : RMSE = %.4f" % (neighbor_size, score(cf_knn, neighbor_size)))

Neighbor size = 10 : RMSE = 3.8311
Neighbor size = 20 : RMSE = 3.8140
Neighbor size = 30 : RMSE = 3.8088
Neighbor size = 40 : RMSE = 3.8056
Neighbor size = 50 : RMSE = 3.8049
Neighbor size = 60 : RMSE = 3.8046

In [ ]:
for neighbor_size in [70, 80, 90, 100]:
    print("Neighbor size = %d : RMSE = %.4f" % (neighbor_size, score(cf_knn, neighbor_size)))

Neighbor size = 70 : RMSE = 3.8044
Neighbor size = 80 : RMSE = 3.8043
Neighbor size = 90 : RMSE = 3.8041
Neighbor size = 100 : RMSE = 3.8041

In [ ]:
for neighbor_size in [110, 120, 130, 140, 150, 160]:
    print("Neighbor size = %d : RMSE = %.4f" % (neighbor_size, score(cf_knn, neighbor_size)))

Neighbor size = 110 : RMSE = 3.8041
Neighbor size = 120 : RMSE = 3.8040
Neighbor size = 130 : RMSE = 3.8040
Neighbor size = 140 : RMSE = 3.8039
Neighbor size = 150 : RMSE = 3.8039
Neighbor size = 160 : RMSE = 3.8039

In [ ]:
for neighbor_size in [200,300,400]:
    print("Neighbor size = %d : RMSE = %.4f" % (neighbor_size, score(cf_knn, neighbor_size)))

Neighbor size = 200 : RMSE = 3.8039
Neighbor size = 300 : RMSE = 3.8039
Neighbor size = 400 : RMSE = 3.8039

In [ ]:
# train 데이터의 user의 rating 평균과 카페의 평점편차 계산 
rating_mean = rating_matrix.mean(axis=1)
rating_bias = (rating_matrix.T - rating_mean).T

def CF_knn_bias(user_id, cafe, neighbor_size=0):
    if cafe in rating_bias:
        # 현 user와 다른 사용자 간의 유사도 가져오기
        sim_scores = user_similarity[user_id].copy()
        # 현 cafe의 평점편차 가져오기
        cafe_ratings = rating_bias[cafe].copy()
        # 현 cafe에 대한 rating이 없는 사용자 삭제
        none_rating_idx = cafe_ratings[cafe_ratings.isnull()].index
        cafe_ratings = cafe_ratings.drop(none_rating_idx)
        sim_scores = sim_scores.drop(none_rating_idx)
        
##### Neighbor size가 지정되지 않은 경우        
        if neighbor_size == 0:
            # 편차로 예측값(편차 예측값) 계산
            prediction = np.dot(sim_scores, cafe_ratings) / sim_scores.sum()
            # 편차 예측값에 현 사용자의 평균 더하기
            prediction = prediction + rating_mean[user_id]
##### Neighbor size가 지정된 경우            
        else:
            # 해당 카페를 평가한 사용자가 최소 2명이 되는 경우에만 계산            
            if len(sim_scores) > 1:
                # 지정된 neighbor size 값과 해당 카페를 평가한 총사용자 수 중 작은 것으로 결정
                neighbor_size = min(neighbor_size, len(sim_scores))
                # array로 바꾸기 (argsort를 사용하기 위함)
                sim_scores = np.array(sim_scores)
                cafe_ratings = np.array(cafe_ratings)
                # 유사도를 순서대로 정렬
                user_idx = np.argsort(sim_scores)
                # 유사도와 rating을 neighbor size만큼 받기
                sim_scores = sim_scores[user_idx][-neighbor_size:]
                cafe_ratings = cafe_ratings[user_idx][-neighbor_size:]
                # 편차로 예측치 계산
                prediction = np.dot(sim_scores, cafe_ratings) / sim_scores.sum()
                # 예측값에 현 사용자의 평균 더하기
                prediction = prediction + rating_mean[user_id]
            else:
                prediction = rating_mean[user_id]
    else:
        prediction = rating_mean[user_id]
    return prediction

In [ ]:
score(CF_knn_bias, 160)

4.049282410478079

### 실제 데이터셋을 활용한 추천시스템

In [ ]:
# 실제로 추천을 해주기 위한 데이터 읽기 (추천을 위해서는 train set이 아닌 전체 데이터를 읽어야 함)
import pandas as pd
ratings = pd.read_csv("ratings_two.csv")
ratings = ratings[['user_id', 'cafe', 'rating']]
ratings['rating'] = ratings['rating'].astype(int)  
rating_matrix = ratings.pivot(values='rating', index='user_id', columns='cafe').fillna(0)

In [ ]:
ratings.head()

   user_id               cafe  rating
0  100bln7         3F로비 한강로3가       5
1  100bln7         카페로비 한강로3가       5
2  100ck0j    공차 이대익스프레스점 대현동       1
3  100ck0j  투썸플레이스 숙대입구역점 남영동       1
4  100ck0j       폴바셋 방배역점 방배동       5

In [ ]:
rating_matrix.head()

cafe,0125커피바 홍은동,044워리어스 당산동1가,089커피앤베이커리 화곡동,1028커피엔디저트 성내동,10인치샌드위치&커피 봉천동,125coffee 갈현동,139COFFEE 전농동,1980벽돌집 신정동,1월의윤슬 내발산동,205도씨 명륜2가,...,히어로보드게임카페 홍대2호점 동교동,히어로스터 신도림동,히어커피 양재동,히얼스유알커피 삼성동,히자우 홍제동,히포커피 대학동점 신림동,히포커피서울대점 서울대점 신림동,히히냥냥 역삼동,힐브레드 마곡동,힘들땐마카롱 신당동
user_id,,,,,,,,,,,,,,,,,,,,,
100bln7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
100ck0j,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
100i22n,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
100ooji,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
100q04c,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
# Cosine similarity 계산
from sklearn.metrics.pairwise import cosine_similarity
matrix_dummy = rating_matrix.copy().fillna(0)
user_similarity = cosine_similarity(matrix_dummy, matrix_dummy)
user_similarity = pd.DataFrame(user_similarity, index=rating_matrix.index, columns=rating_matrix.index)

# 전체 데이터의 user의 rating 평균과 카페의 평점편차 계산 
rating_mean = rating_matrix.mean(axis=1)
rating_bias = (rating_matrix.T - rating_mean).T

In [ ]:
rating_mean

user_id
100bln7    0.001917
100ck0j    0.001342
100i22n    0.003834
100ooji    0.001917
100q04c    0.013612
             ...
vv2c9h     0.001534
vv73qf     0.001534
vvcfbq     0.001342
vvkrvp     0.001917
vvrsk6     0.001150
Length: 7035, dtype: float64

In [ ]:
rating_bias

cafe,0125커피바 홍은동,044워리어스 당산동1가,089커피앤베이커리 화곡동,1028커피엔디저트 성내동,10인치샌드위치&커피 봉천동,125coffee 갈현동,139COFFEE 전농동,1980벽돌집 신정동,1월의윤슬 내발산동,205도씨 명륜2가,...,히어로보드게임카페 홍대2호점 동교동,히어로스터 신도림동,히어커피 양재동,히얼스유알커피 삼성동,히자우 홍제동,히포커피 대학동점 신림동,히포커피서울대점 서울대점 신림동,히히냥냥 역삼동,힐브레드 마곡동,힘들땐마카롱 신당동
user_id,,,,,,,,,,,,,,,,,,,,,
100bln7,-0.001917,-0.001917,-0.001917,-0.001917,-0.001917,-0.001917,-0.001917,-0.001917,-0.001917,-0.001917,...,-0.001917,-0.001917,-0.001917,-0.001917,-0.001917,-0.001917,-0.001917,-0.001917,-0.001917,-0.001917
100ck0j,-0.001342,-0.001342,-0.001342,-0.001342,-0.001342,-0.001342,-0.001342,-0.001342,-0.001342,-0.001342,...,-0.001342,-0.001342,-0.001342,-0.001342,-0.001342,-0.001342,-0.001342,-0.001342,-0.001342,-0.001342
100i22n,-0.003834,-0.003834,-0.003834,-0.003834,-0.003834,-0.003834,-0.003834,-0.003834,-0.003834,-0.003834,...,-0.003834,-0.003834,-0.003834,-0.003834,-0.003834,-0.003834,-0.003834,-0.003834,-0.003834,-0.003834
100ooji,-0.001917,-0.001917,-0.001917,-0.001917,-0.001917,-0.001917,-0.001917,-0.001917,-0.001917,-0.001917,...,-0.001917,-0.001917,-0.001917,-0.001917,-0.001917,-0.001917,-0.001917,-0.001917,-0.001917,-0.001917
100q04c,-0.013612,-0.013612,-0.013612,-0.013612,-0.013612,-0.013612,-0.013612,-0.013612,-0.013612,-0.013612,...,-0.013612,-0.013612,-0.013612,-0.013612,-0.013612,-0.013612,-0.013612,-0.013612,-0.013612,-0.013612
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
vv2c9h,-0.001534,-0.001534,-0.001534,-0.001534,-0.001534,-0.001534,-0.001534,-0.001534,-0.001534,-0.001534,...,-0.001534,-0.001534,-0.001534,-0.001534,-0.001534,-0.001534,-0.001534,-0.001534,-0.001534,-0.001534
vv73qf,-0.001534,-0.001534,-0.001534,-0.001534,-0.001534,-0.001534,-0.001534,-0.001534,-0.001534,-0.001534,...,-0.001534,-0.001534,-0.001534,-0.001534,-0.001534,-0.001534,-0.001534,-0.001534,-0.001534,-0.001534
vvcfbq,-0.001342,-0.001342,-0.001342,-0.001342,-0.001342,-0.001342,-0.001342,-0.001342,-0.001342,-0.001342,...,-0.001342,-0.001342,-0.001342,-0.001342,-0.001342,-0.001342,-0.001342,-0.001342,-0.001342,-0.001342
vvkrvp,-0.001917,-0.001917,-0.001917,-0.001917,-0.001917,-0.001917,-0.001917,-0.001917,-0.001917,-0.001917,...,-0.001917,-0.001917,-0.001917,-0.001917,-0.001917,-0.001917,-0.001917,-0.001917,-0.001917,-0.001917
vvrsk6,-0.001150,-0.001150,-0.001150,-0.001150,-0.001150,-0.001150,-0.001150,-0.001150,-0.001150,-0.001150,...,-0.001150,-0.001150,-0.001150,-0.001150,-0.001150,-0.001150,-0.001150,-0.001150,-0.001150,-0.001150

In [ ]:
# 추천하기
def recommender(user, n_items):
    # 현재 사용자의 모든 아이템에 대한 예상 평점 계산
    predictions = []
    rated_index = rating_matrix.loc[user][rating_matrix.loc[user] > 0].index    # 이미 평가한 카페 확인
    items = rating_matrix.loc[user].drop(rated_index)
    for item in items.index:
        predictions.append(CF_knn_bias(user, item))                               # 예상평점 계산
    recommendations = pd.Series(data=predictions, index=items.index, dtype=float)
    recommendations = recommendations.sort_values(ascending=False)[:n_items]    # 예상평점이 가장 높은 카페 선택
    return recommendations

In [ ]:
ratings[ratings['cafe'] == '안다르커피 창천동']

      user_id       cafe  rating
559   10l9o2l  안다르커피 창천동       5
1596  12c6sec  안다르커피 창천동       5
3022  14los79  안다르커피 창천동       4

In [ ]:
# 카페 추천 함수 부르기
recommender('14los79', 5)

cafe
르솔레이 연희동        0.238810
내자상회 내자동        0.210108
포트레이트커피바 망원동    0.161289
꽁티드툴레아 신사동      0.151501
어라운드데이 성수동1가    0.146821
dtype: float64

In [ ]:
recommender('10l9o2l', 5)

cafe
라라브레드 공릉점 공릉동        0.261886
테라로사 포스코센터점 대치동      0.211963
맥심플랜트 한남동            0.199247
투썸플레이스신촌점 신촌점 창천동    0.165095
943킹스크로스 서교동         0.131703
dtype: float64

In [ ]:
recommender('12c6sec',5)

cafe
땡스오트 연남동         0.153214
설빙신촌점 신촌점 창천동    0.144408
카페노티드 안국점 재동     0.127503
플루프 연남동          0.117379
후엘고 염리동          0.106747
dtype: float64

#### 거리 지표 포함

In [ ]:
public_df = pd.read_csv("publicdata_cafe_lastdrop.csv")

In [ ]:
public_df.head()

,상가업소번호,상호명,지점명,상권업종대분류코드,상권업종대분류명,상권업종중분류코드,상권업종중분류명,상권업종소분류코드,상권업종소분류명,표준산업분류코드,...,도로명주소,구우편번호,신우편번호,동정보,층정보,호정보,경도,위도,이름,cafe
0,20659878,커피빈,코리아대학로대명거리점,Q,음식,Q12,커피점/카페,Q12A01,커피전문점/카페/다방,I56220,...,서울특별시 종로구 대명길 25,110524,3078.0,NaN,3,NaN,127.000171,37.583149,커피빈 코리아대학로대명거리점,커피빈 코리아대학로대명거리점 명륜4가
1,20676428,요거프레소,쌍문점,Q,음식,Q12,커피점/카페,Q12A01,커피전문점/카페/다방,I56220,...,서울특별시 도봉구 도당로 7,132030,1385.0,NaN,1,NaN,127.034746,37.658728,요거프레소 쌍문점,요거프레소 쌍문점 쌍문동
2,28491095,우성커피숍,NaN,Q,음식,Q12,커피점/카페,Q12A01,커피전문점/카페/다방,I56220,...,서울특별시 양천구 오목로 48,158090,8029.0,NaN,1,NaN,126.842935,37.522055,우성커피숍,우성커피숍 신월동
3,23260840,버블베어,NaN,Q,음식,Q12,커피점/카페,Q12A01,커피전문점/카페/다방,I56220,...,서울특별시 강서구 금낭화로 167,157788,7509.0,NaN,1,NaN,126.813358,37.580941,버블베어,버블베어 방화동
4,22206830,알뤼르,NaN,Q,음식,Q12,커피점/카페,Q12A01,커피전문점/카페/다방,I56220,...,서울특별시 강남구 삼성로85길 33,135280,6196.0,NaN,NaN,NaN,127.054731,37.504378,알뤼르,알뤼르 대치동

In [ ]:
# 추천하기
def content_recommender2(user, n_items, address):
    # 현재 사용자의 모든 아이템에 대한 예상 평점 계산
    predictions = []
    rated_index = rating_matrix.loc[user][rating_matrix.loc[user] > 0].index    # 이미 평가한 카페 확인
    items = rating_matrix.loc[user].drop(rated_index)
    for item in items.index:
        predictions.append(CF_knn_bias(user, item))                               # 예상평점 계산
    r = pd.Series(data=predictions, index=items.index, dtype=float)
    r = r.sort_values(ascending=False)   # 예상평점이 가장 높은 카페 선택
    recom_cafe = pd.DataFrame(predictions, index=r.index)
     # 거리지표 추가
    recommendations = pd.merge(recom_cafe, public_df.set_index('cafe')[['시군구명','도로명주소']], left_index=True,right_index=True,how='left')
    # address 부분
    recommendations = recommendations[recommendations['시군구명']==address]
    R = recommendations.sort_values(by=[0], axis=0, ascending = False)[1:n_items+2]
    #recommendations = R.iloc[:n_items,:]
    R.columns = ['Predictions','시군구명','도로명주소']
    R['Predictions'] = R['Predictions'] 
    R = R.drop([R.index[9]])

    return R

In [ ]:
# 카페 추천 함수 부르기
content_recommender2('14los79', 5, '서대문구')

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

                 Predictions  시군구명                도로명주소
cafe
꾼낚시카페 홍대신촌점 창천동     4.087248  서대문구    서울특별시 서대문구 명물길 66
프로토콜 연희동            4.087248  서대문구   서울특별시 서대문구 연희로 109
팔공티 이대점 대현동         4.080898  서대문구  서울특별시 서대문구 이화여대길 48
이디야서대문점2호 냉천동       4.048983  서대문구   서울특별시 서대문구 통일로 141
청년다방 신촌점 대현동        4.044759  서대문구   서울특별시 서대문구 신촌로 139

In [ ]:
# 카페 추천 함수 부르기
content_recommender2('10l9o2l', 10, '서대문구')

                  Predictions  시군구명                  도로명주소
cafe
바이트앤십 냉천동            4.075672  서대문구     서울특별시 서대문구 독립문로 65
스튜디오웝 대신동            4.053682  서대문구     서울특별시 서대문구 성산로 539
COFFEEZOE 대현동        4.038653  서대문구  서울특별시 서대문구 이화여대길 50-6
카시코이 연희동             4.038653  서대문구   서울특별시 서대문구 성산로 253-4
이디야커피 홍은사거리점 홍은동     4.030423  서대문구     서울특별시 서대문구 통일로 510
커피가게동경 연희점 연희동       4.028943  서대문구     서울특별시 서대문구 연희맛로 23
프레쉬스터디카페 신촌점 창천동     4.022795  서대문구      서울특별시 서대문구 명물길 10
에스크투데이 연희동           4.020782  서대문구  서울특별시 서대문구 연희로11가길 56
이디야커피 아현역점 북아현동      4.020175  서대문구   서울특별시 서대문구 신촌로35길 10
카페 제이미쉬 북가좌동         4.017388  서대문구     서울특별시 서대문구 수색로 102

In [ ]:
content_recommender2('12c6sec', 5, '서대문구')

                  시군구명                 도로명주소
cafe
설빙신촌점 신촌점 창천동     서대문구     서울특별시 서대문구 연세로 19
프로토콜 연희동          서대문구    서울특별시 서대문구 연희로 109
스타벅스 신촌아트레온점 창천동  서대문구    서울특별시 서대문구 신촌로 129
컨시어지커피 연희동        서대문구      서울특별시 서대문구 증가로 1
베이직커피 북아현동        서대문구  서울특별시 서대문구 신촌로29길 14

### CF 정확도 개선2

#### 사용자 평가경향 고려

In [ ]:
# CF 정확도 개선

# 사용자별 공통 평가 수 계산
rating_binary1 = np.array((rating_matrix > 0).astype(float))
rating_binary2 = rating_binary1.T
counts = np.dot(rating_binary1, rating_binary2)
counts = pd.DataFrame(counts, index=rating_matrix.index, columns=rating_matrix.index).fillna(0)

def CF_knn_bias_sig(user_id, cafe, neighbor_size=0):
    if cafe in rating_bias:
        # 현 user와 다른 사용자 간의 유사도 가져오기
        sim_scores = user_similarity[user_id]
        # 현 cafe의 평점편차 가져오기
        cafe_ratings = rating_bias[cafe]
        # 현 cafe에 대한 rating이 없는 사용자 표시
        no_rating = cafe_ratings.isnull()
        # 현 사용자와 다른 사용자간 공통 평가 아이템 수 가져오기 
        common_counts = counts[user_id]
        # 공통으로 평가한 카페의 수가 SIG_LEVEL보다 낮은 사용자 표시
        low_significance = common_counts < SIG_LEVEL
        # 평가를 안 하였거나, SIG_LEVEL이 기준 이하인 user 제거
        none_rating_idx = cafe_ratings[no_rating | low_significance].index
        cafe_ratings = cafe_ratings.drop(none_rating_idx)
        sim_scores = sim_scores.drop(none_rating_idx)
##### Neighbor size가 지정되지 않은 경우        
        if neighbor_size == 0:
            # 편차로 예측값(편차 예측값) 계산
            prediction = np.dot(sim_scores, cafe_ratings) / sim_scores.sum()
            # 편차 예측값에 현 사용자의 평균 더하기
            prediction = prediction + rating_mean[user_id]
##### Neighbor size가 지정된 경우            
        else:
            # 해당 카페를 평가한 사용자가 최소 MIN_RATINGS 이상인 경우에만 계산            
            if len(sim_scores) > MIN_RATINGS:
                # 지정된 neighbor size 값과 해당 카페를 평가한 총사용자 수 중 작은 것으로 결정
                neighbor_size = min(neighbor_size, len(sim_scores))
                # array로 바꾸기 (argsort를 사용하기 위함)
                sim_scores = np.array(sim_scores)
                cafe_ratings = np.array(cafe_ratings)
                # 유사도를 순서대로 정렬
                user_idx = np.argsort(sim_scores)
                # 유사도와 rating을 neighbor size만큼 받기
                sim_scores = sim_scores[user_idx][-neighbor_size:]
                cafe_ratings = cafe_ratings[user_idx][-neighbor_size:]
                # 편차로 예측치 계산
                prediction = np.dot(sim_scores, cafe_ratings) / sim_scores.sum()
                # 예측값에 현 사용자의 평균 더하기
                prediction = prediction + rating_mean[user_id]
            else:
                prediction = rating_mean[user_id]
    else:
        prediction = rating_mean[user_id]
    return prediction

In [ ]:
SIG_LEVEL = 3
MIN_RATINGS = 2
score(CF_knn_bias_sig, 160)

3.9841417700711603

In [ ]:
#추천하기

# 전체 데이터의 user의 rating 평균과 카페의 평점편차 계산 
rating_mean = rating_matrix.mean(axis=1)
rating_bias = (rating_matrix.T - rating_mean).T

# 전체 데이터에 대해서 사용자별 공통 평가 수 계산
rating_binary1 = np.array((rating_matrix > 0).astype(float))
rating_binary2 = rating_binary1.T
counts = np.dot(rating_binary1, rating_binary2)
counts = pd.DataFrame(counts, index=rating_matrix.index, columns=rating_matrix.index).fillna(0)

# 추천하기
def recommender(user, n_items, neighbor_size):
    # 현재 사용자의 모든 아이템에 대한 예상 평점 계산
    predictions = []
    rated_index = rating_matrix.loc[user][rating_matrix.loc[user] > 0].index    # 이미 평가한 카페 확인
    items = rating_matrix.loc[user].drop(rated_index)
    for item in items.index:
        predictions.append(CF_knn_bias_sig(user, item, neighbor_size))       # 예상평점 계산
    recommendations = pd.Series(data=predictions, index=items.index, dtype=float)
    recommendations = recommendations.sort_values(ascending=False)[:n_items]    # 예상평점이 가장 높은 카페 선택
    return recommendations

# 카페 추천 함수 부르기
recommender('10l9o2l', 10, 160)

cafe
0125커피바 홍은동         0.001342
청키파이 대현동            0.001342
친구네과자집 자양동          0.001342
치키차카초코 마곡점 마곡동      0.001342
치유커피 한남동            0.001342
치:와와 신당동            0.001342
츄로101삼청점 삼청점 삼청동    0.001342
춘삼월 중계동             0.001342
추억속의그다방 서초동         0.001342
쵸비하우스 석촌동           0.001342
dtype: float64

### 아이템 기반 CF

In [ ]:
# train set의 모든 가능한 아이템 pair의 Cosine similarities 계산
from sklearn.metrics.pairwise import cosine_similarity
rating_matrix_t = np.transpose(rating_matrix)
matrix_dummy = rating_matrix_t.copy().fillna(0)
item_similarity = cosine_similarity(matrix_dummy, matrix_dummy)
item_similarity = pd.DataFrame(item_similarity, index=rating_matrix_t.index, columns=rating_matrix_t.index)

# 주어진 카페의 가중평균 rating을 계산하는 함수, 
# 가중치는 주어진 아이템과 다른 아이템 간의 유사도(item_similarity)
def CF_IBCF(user_id, cafe, user_rating):
    if cafe in item_similarity:      # 현재 카페가 train set에 있는지 확인
        # 현재 카페와 다른 카페의 similarity 값 가져오기
        sim_scores = item_similarity[cafe]
        # 현 사용자의 모든 rating 값 가져오기
        user_rating = rating_matrix_t[user_id]
        # 사용자가 평가하지 않은 카페 index 가져오기
        non_rating_idx = user_rating[user_rating.isnull()].index
        # 사용자가 평가하지 않은 카페 제거
        user_rating = user_rating.dropna()
        # 사용자가 평가하지 않은 카페의 similarity 값 제거
        sim_scores = sim_scores.drop(non_rating_idx)
        # 현 카페에 대한 예상 rating 계산, 가중치는 현 카페와 사용자가 평가한 카페의 유사도
        mean_rating = np.dot(sim_scores, user_rating) / sim_scores.sum()
    else:
        mean_rating = 3.0
    return mean_rating

In [ ]:
# 정확도 계산
score(CF_IBCF)

2.789600418536724